### PR TITLE
Map Generation

### PR DESCRIPTION
**Pull request by Tardo**
# Map Generation
- Workflow (With MapGen Enabled):
  - Server Init: Check if the currect "sv_map"+"sv_mapgen_seed" exists. If not, create a empty map (It will be our canvas) if yes.. load it.
  - Server Load: Check if the map was generated (is a empty map). If not, do nothing.. if yes, fill the empty map.

_** Made in this way because perhaps in the future want edit the map live and save it._
- New server variables:
  - sv_mapgen: Enable/Disable map generation
  - sv_mapgen_seed: Seed used for map generation
  - sv_mapgen_width: Width of the generated map
  - sv_mapgen_height: Height of the generated map

## ToDo
- [x] ~~Fix Skip Generation~~
- [x] ~~Generate Spawns~~
- [x] ~~Coherent Maps~~
- [ ] Apply Auto-Mapper Rules

## Current Status
Example #1

---

**DON'T MERGE... WORK IN PROGRESS**

### CODE REVIEW

**Comment by ObaniGemini** [comment]
Couldn't be less precise :p

**Comment by Tardo** [comment]
@ObaniGemini Description Updated ;)

**Comment by ObaniGemini** [comment]
Ok so this is really for procedural map generation. I don't get how is that that you guys are so crazy... :D
Good luck with that, you have all my moral support.

**Comment by Siile** [comment]
This is awesome! Let me know when ready for merge. I have some ideas for linear map generating as well, can't wait to try them out. :)

**Comment by Tardo** [comment]
@Siile You don't want terrain maps no? Perhaps my works finish here... you can merge... but best work on my branch. :) I need know how you like work with this for implement a good way to ref. the tile to draw... (Tile ID: 1 not is the same in main_grass.png that in unhookable.png)

Now the code only is ready for work with "main_grass.png" but is easy extend for work with the selected external tileset.

**Comment by Siile** [comment]
My plan is to load existing map with correct layers and background already done, and the generate separate layers using different rules.

E.g. generate walls first, run auto mapper for them, then generate boxes to a separate layer, run auto mapper with different rules, generate platforms...

**Comment by Siile** [comment]
On windows:

[ 1/15] #1 c++ src/engine/shared/noise.cpp
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\random(1604) : er
ror C2064: term does not evaluate to a function taking 0 arguments
        c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\random(15
56) : see reference to function template instantiation 'void std::tr1::mersenne_
twister<_Ty,_Wx,_Nx,_Mx,_Rx,_Px,_Ux,_Sx,_Bx,_Tx,_Cx,_Lx>::seed<_Gen>(_Gen &,bool
)' being compiled
        with
        [
            _Ty=unsigned long,
            _Wx=32,
            _Nx=624,
            _Mx=397,
            _Rx=31,
            _Px=-1727483681,
            _Ux=11,
            _Sx=7,
            _Bx=-1658038656,
            _Tx=15,
            _Cx=-272236544,
            _Lx=18,
            _Gen=uint32_t
        ]
        src/engine/shared/noise.cpp(10) : see reference to function template ins
tantiation 'std::tr1::mersenne_twister<_Ty,_Wx,_Nx,_Mx,_Rx,_Px,_Ux,_Sx,_Bx,_Tx,_
Cx,_Lx>::mersenne_twister<uint32_t>(_Gen &)' being compiled
        with
        [
            _Ty=unsigned long,
            _Wx=32,
            _Nx=624,
            _Mx=397,
            _Rx=31,
            _Px=-1727483681,
            _Ux=11,
            _Sx=7,
            _Bx=-1658038656,
            _Tx=15,
            _Cx=-272236544,
            _Lx=18,
            _Gen=uint32_t
        ]
bam: 'objs/engine/shared/noise.obj' error 2
bam: error: a build step failed

**Comment by Tardo** [comment]
Visual Studio 10.0?? Why not Visual Basic 6.0? xDD i think that these version of Visual Studio isn't compatible with C++11 ... required by Perlin Noise part... but if you don't like terrain based maps.. need delete these part... and you will can compile ninslash again with your older IDE :P

**Comment by Siile** [comment]
Hey, visual studio 2010 is only 8 years old. :)

I don't necessarily need perlin noise. What I really need is possibility to load existing map and alter the tiles in some of it's layers.

**Comment by Siile** [comment]
Is there a way to load a map and generate some of it's layers? Generating all background layers is way too hard.

**Comment by Tardo** [comment]
Hi! ook... these days i have a lot of work to do... but i will try to do it next weekend!
 - Remove Perlin Noise
 - Apply Auto Mapper Rules

Anything else? Cheers!

**Comment by Siile** [comment]
Auto mapper rules would be more than enough. :)

Now generated maps look like this:
http://ninslash.com/png/gen2.png

I applied auto mapper rules manually, but everything else is generated.

**Comment by Tardo** [comment]
Looks promising!

P.S: Would be nice if you commit changes here for traceability ;)

**Comment by Siile** [comment]
You don't mind if I merge and override with my changes?

**Pull request merged**
