### PR TITLE
New mask: Mask of armor

### PR DESCRIPTION
**Pull request by Jogius**
Added new mask that regenerates armor

### CODE REVIEW

**Comment by ObaniGemini** [comment]
Did you write character.cpp ?

**Comment by Jogius** [comment]
> Did you write character.cpp ?
Yes I did, did I miss another one?
Ninslash\src\game\server\character.cpp

**Comment by ObaniGemini** [comment]
1 : is this working ?
2 : I don't think this would be acceptable as you seem to have copied a whole codefile instead of modifying it

**Comment by Jogius** [comment]
1. As far as my testing goes it does what it's supposed to do, the other masks still work and it spawns on the map from the random generator.
2. I think it is okay, as I worked together with Siile while creating this and he told me to do a pull request as soon as it works.

**Comment by ObaniGemini** [comment]
The only problem of this PR so far is that the whole "character.cpp" code is shown as modified, or newly created, while it's not the case. I suggest you save what you have modified and make a new PR that shows a proper git diff (because this falses the contributions log).

@Siile do you agree ?

**Comment by Jogius** [comment]
> The only problem of this PR so far is that the whole "character.cpp" code is shown as modified, or newly created, while it's not the case. I suggest you save what you have modified and make a new PR that shows a proper git diff (because this falses the contributions log).
> 
> @Siile do you agree ?

Why does it show the whole character.cpp as changed tho while on the others its just single lines? Is it just because I added new lines and by that I changed the number of the others?

**Comment by ObaniGemini** [comment]
I don't think so, I just think you somehow messed up the diff detection

**Comment by Jogius** [comment]
> I don't think so, I just think you somehow messed up the diff detection

Hmm, I was searching for a fix but for some reason it keeps saying that in the character.cpp I changed over 2000 lines.

**Comment by ObaniGemini** [comment]
The solution is simple but boring to do : make a backup of your changed files, make a new repo and re-add your changes there. Then, make a new clean Pull Request or clean that one with a command like `git reset HEAD~1`

**Comment by Jogius** [comment]
> The solution is simple but boring to do : make a backup of your changed files, make a new repo and re-add your changes there. Then, make a new clean Pull Request or clean that one with a command like `git reset HEAD~1`

Thats how I did it the first time tho

**Pull request closed without merging**
